# Generated by Django 4.0.6 on 2022-08-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startno', models.IntegerField(default=0)),
                ('stopno', models.IntegerField(default=0)),
                ('outdata1', models.TextField(default=None)),
                ('outdata2', models.TextField(default=None)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='primeno',
        ),
    ]
